// <auto-generated />
using System;
using ApiUsersRecipeTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiUsersRecipeTool.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240529074838_ListBuy")]
    partial class ListBuy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiUsersRecipeTool.Models.BuyList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BuyLists");
                });

            modelBuilder.Entity("ApiUsersRecipeTool.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BuyListId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BuyListId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("ApiUsersRecipeTool.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ApiUsersRecipeTool.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiUsersRecipeTool.Models.BuyList", b =>
                {
                    b.HasOne("ApiUsersRecipeTool.Models.User", null)
                        .WithMany("BuyLists")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ApiUsersRecipeTool.Models.Ingredient", b =>
                {
                    b.HasOne("ApiUsersRecipeTool.Models.BuyList", "BuyList")
                        .WithMany("Ingredients")
                        .HasForeignKey("BuyListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyList");
                });

            modelBuilder.Entity("ApiUsersRecipeTool.Models.Recipe", b =>
                {
                    b.HasOne("ApiUsersRecipeTool.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiUsersRecipeTool.Models.BuyList", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("ApiUsersRecipeTool.Models.User", b =>
                {
                    b.Navigation("BuyLists");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
